application: robohornet-benchmark
version: iframe
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: PIL
  version: latest

handlers:
- url: /issue.*
  script: voting.app
- url: /
  static_files: static/robohornet.html
  upload: static/robohornet.html
- url: /(.*)
  static_files: static/\1
  upload: static/.*